[package]
name = "postly-app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Postly's native Rust desktop request workspace"

[[bin]]
name = "postly-gui"
path = "src/main.rs"

[dependencies]
base64.workspace = true
chrono.workspace = true
eframe.workspace = true
futures-util.workspace = true
http.workspace = true
postly-core = { path = "../postly-core" }
prost.workspace = true
prost-reflect.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tonic.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true
